const TYPES = {
    SET_USER_INFO: 'SET_USER_INFO',
    SET_ERROR: 'SET_ERROR',
    SET_NOTIFY_MESSAGE: 'SET_NOTIFY_MESSAGE',
    SET_MUSIC_VOLUME: 'SET_MUSIC_VOLUME',
    SET_SOUND_VOLUME: 'SET_SOUND_VOLUME',
    SET_APP_LOADING: 'SET_APP_LOADING'
}

export default TYPES