const TYPES = {
    SET_USER_INFO: 'SET_USER_INFO',
    SET_ERROR: 'SET_ERROR',
    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
    SET_NOTIFY_MESSAGE: 'SET_NOTIFY_MESSAGE',
    SET_MUSIC_VOLUME: 'SET_MUSIC_VOLUME',
    SET_SOUND_VOLUME: 'SET_SOUND_VOLUME',
    ADD_APP_LOADING: 'ADD_APP_LOADING',
    DISABLE_INIT_LOADING: 'DISABLE_INIT_LOADING',
    REMOVE_APP_LOADING: 'REMOVE_APP_LOADING',
    SET_APP_CONTANTS: 'SET_APP_CONTANTS',
    SET_ACTIVE_BATTLE: 'SET_ACTIVE_BATTLE'
}

export default TYPES